### ISSUE TITLE
scala.version set to 2.10.0. Not working in current release

### ISSUE THREAD

**Issue by qiemem** [NetLogo/Network-Extension#3]
In build.sbt, the scala.version is set to 2.10. I get an exception whenever I try to do anything in the 5.2 rc, and I suspect 5.1 will be the same. Even though this extension is deprecated, it's still bundled and should therefore actually work.

**Comment by frankduncan** [comment]
Hmmm, this seems to be working for me on linux.  I just put in the following simple model:

````
extensions [ network ]

undirected-link-breed [ x y ]

to go
  ask turtle 1 [ show network:link-distance turtle 0 x ]
end
````

That model worked (returning false, of course) in 5.1.0, 5.2.0-RC3 and using ./sbt run from a NetLogo checkout.  Am I doing something wrong?

**Comment by qiemem** [comment]
Sorry, I messed up. You're right. Though I'm not sure why it's working.

**Comment by SethTisue** [comment]
@qiemem you were probably working off the wrong branch in the nw extension repo
